#!/bin/bash
apt update
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running

puppet resource file /tmp/3834975Y ensure=absent force=true
puppet resource file /tmp/3834975Y ensure=directory recurse=true
puppet resource file /tmp/3834975Y/work ensure=directory recurse=true

cd /tmp/3834975Y/work
git clone https://github.com/wesley-if/operate-repo-3834975Y.git
cp -p /tmp/3834975Y/work/operate-repo-3834975Y/index.html_3834975Y /var/www/html/index.html
